# Generated by nixos-generate-config; keep host-specific disks and kernel modules here.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/505b9740-458e-4164-bc8b-c737dce975c9";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/62B4-8D03";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
      "noatime"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/65a6fa7f-72fd-419f-9cf0-b5df22933976"; }
  ];

  # Resume from the disk-backed swap partition.  zram remains the preferred
  # runtime swap, but it cannot retain a hibernation image across power-off.
  boot.resumeDevice = "/dev/disk/by-uuid/65a6fa7f-72fd-419f-9cf0-b5df22933976";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
