#!/usr/bin/env dash


# kitty --directory "$HOME/documents/notes" sh -c 'nvim "$(/home/jefaturico/.scripts/fzf-rg)"'
foot -D "$HOME/documents/notes" -e sh -c 'nvim "$(/home/jefaturico/.scripts/fzf-rg)"'
