#!/usr/bin/env dash

notify() {
  VOLUME_INFO=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
  CURRENT_VOLUME_INT=$(printf '%s\n' "$VOLUME_INFO" |
    awk '{printf "%.0f", $2 * 100}')
  CURRENT_VOLUME_TEXT=$(printf '%s\n' "$VOLUME_INFO" |
    awk '{
      if ($3 == "[MUTED]") printf "Volume: muted"
      else printf "Volume: %.0f%%", $2 * 100
    }')
  notify-send \
    -a osd -t 500 \
    -h int:value:"$CURRENT_VOLUME_INT" \
    -h string:x-canonical-private-synchronous:volume \
    "$CURRENT_VOLUME_TEXT"
}

if [ "$1" = "up" ]; then
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1+ -l 1.0
  notify

elif [ "$1" = "down" ]; then
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1-
  notify

elif [ "$1" = "mute" ]; then
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
  notify

else
  printf "Usage:\nvolume up\nvolume down\nvolume mute"; exit 1
fi
