# Generated by nixos-generate-config; keep host-specific disks and kernel modules here.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "uas"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fbd1e66b-d181-4227-be0d-c8c1890ef74e";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/e13eb5af-e843-4121-b327-dcdc55b24114";
    fsType = "ext4";
    options = [
      "defaults"
      "nofail"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F016-8AFA";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
      "noatime"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/f4bad740-69c7-4702-874f-e2bb973b67eb";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
