anchor=top-center
background-color={{ colors.surface.dark.hex }}b3
border-color={{ colors.surface.dark.hex }}b3
border-radius=15
border-size=0
default-timeout=5000
font=JetBrainsMono Nerd Font 12
max-visible=3
outer-margin=20
padding=12
progress-color=over {{ colors.primary.dark.hex }}66
text-color={{ colors.on_surface.dark.hex }}ff
width=360

[urgency=low]
text-color={{ colors.on_surface_variant.dark.hex }}ff

[urgency=critical]
text-color={{ colors.error.dark.hex }}ff

[app-name=volume]
anchor=center

[app-name=brightness]
anchor=center

[mode=light]
background-color={{ colors.surface.light.hex }}ff
border-color={{ colors.surface.light.hex }}ff
progress-color=over {{ colors.primary.light.hex }}66
text-color={{ colors.on_surface.light.hex }}ff

[mode=light urgency=low]
text-color={{ colors.on_surface_variant.light.hex }}ff

[mode=light urgency=critical]
text-color={{ colors.error.light.hex }}ff
