background_dark='{{ colors.surface.dark.hex_stripped }}'
foreground_dark='{{ colors.on_surface.dark.hex_stripped }}'
cursor_dark='{{ colors.primary.dark.hex_stripped }}'
terminal_colors_dark=(
  '{{ colors.surface.dark.hex_stripped }}'
  '{{ colors.error.dark.hex_stripped }}'
  '{{ colors.tertiary.dark.hex_stripped }}'
  '{{ colors.secondary.dark.hex_stripped }}'
  '{{ colors.primary.dark.hex_stripped }}'
  '{{ colors.tertiary_fixed_dim.dark.hex_stripped }}'
  '{{ colors.secondary_fixed_dim.dark.hex_stripped }}'
  '{{ colors.on_surface_variant.dark.hex_stripped }}'
  '{{ colors.outline.dark.hex_stripped }}'
  '{{ colors.error_container.dark.hex_stripped }}'
  '{{ colors.tertiary_container.dark.hex_stripped }}'
  '{{ colors.secondary_container.dark.hex_stripped }}'
  '{{ colors.primary_container.dark.hex_stripped }}'
  '{{ colors.secondary_fixed.dark.hex_stripped }}'
  '{{ colors.tertiary_fixed.dark.hex_stripped }}'
  '{{ colors.on_surface.dark.hex_stripped }}'
)
background_light='{{ colors.surface.light.hex_stripped }}'
foreground_light='{{ colors.on_surface.light.hex_stripped }}'
cursor_light='{{ colors.primary.light.hex_stripped }}'
terminal_colors_light=(
  '{{ colors.surface.light.hex_stripped }}'
  '{{ colors.error.light.hex_stripped }}'
  '{{ colors.tertiary.light.hex_stripped }}'
  '{{ colors.secondary.light.hex_stripped }}'
  '{{ colors.primary.light.hex_stripped }}'
  '{{ colors.tertiary_fixed_dim.light.hex_stripped }}'
  '{{ colors.secondary_fixed_dim.light.hex_stripped }}'
  '{{ colors.on_surface_variant.light.hex_stripped }}'
  '{{ colors.outline.light.hex_stripped }}'
  '{{ colors.error_container.light.hex_stripped }}'
  '{{ colors.tertiary_container.light.hex_stripped }}'
  '{{ colors.secondary_container.light.hex_stripped }}'
  '{{ colors.primary_container.light.hex_stripped }}'
  '{{ colors.secondary_fixed.light.hex_stripped }}'
  '{{ colors.tertiary_fixed.light.hex_stripped }}'
  '{{ colors.on_surface.light.hex_stripped }}'
)
