#!/bin/sh

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

sh -c "~/.wbg"

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
systemctl --user start aurora.target graphical-session.target      riverctl background-color 0x000000

riverctl border-width 0
rivertile -view-padding 0 -outer-padding 0 &
riverctl default-layout rivertile

riverctl keyboard-layout -options "compose:menu,ctrl:nocaps" es

riverctl set-repeat 50 200
riverctl focus-follows-cursor normal

riverctl input pointer-1267-12397-ELAN2202:00_04F3:306D_Touchpad natural-scroll enabled
riverctl input pointer-1267-12397-ELAN2202:00_04F3:306D_Touchpad tap enabled

riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad natural-scroll enabled
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad tap enabled
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad pointer-accel 0.4

riverctl map normal Mod4 O           focus-view next
riverctl map normal Mod4+Shift O     focus-view previous
riverctl map normal Super plus send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super minus send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super period send-layout-cmd rivertile "main-ratio 0.6"
riverctl map normal Super+Shift plus send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift minus send-layout-cmd rivertile "main-count -1"
riverctl map normal Super colon send-layout-cmd rivertile "main-count 1"
riverctl map normal Mod4 Space zoom

riverctl map normal Mod4 M       toggle-fullscreen

riverctl map-pointer normal Mod4 BTN_LEFT   move-view
riverctl map-pointer normal Mod4 BTN_RIGHT  resize-view
riverctl map-pointer normal Mod4 BTN_MIDDLE toggle-float
riverctl map normal Mod4+Shift Space toggle-float

riverctl map normal Mod4 Q       spawn "riverctl close"
riverctl map normal Mod4+Shift Return       spawn "foot"
riverctl map normal Mod4 Return       spawn "emacsclient -c"
riverctl map normal Mod4 P            spawn fuzzel

riverctl map normal Mod4+Shift Escape exit

ariverctl map normal Mod4 B       spawn "river-setbg"
riverctl map normal Mod4+Shift B spawn "river-setbg -r"

riverctl map normal Mod4 D spawn "wdoc-find"
riverctl map normal Mod4 W spawn "fuzzel-bookmarks"
riverctl map normal Mod4+Shift W spawn "fuzzel-bookmarks --add"

riverctl map -repeat normal None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+"
riverctl map -repeat normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-"
riverctl map         normal None XF86AudioMute        spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

riverctl map -repeat normal None XF86MonBrightnessUp   spawn "brightnessctl set +10%"
riverctl map -repeat normal None XF86MonBrightnessDown spawn "brightnessctl set 10%-"

riverctl map normal Mod4 R spawn "sh -c 'pkill rivertile; ~/.config/river/init'"


# Keys 1-9 -> Tags 1-9
for i in {1..9}; do
    tags=$((1 << (i - 1)))
    riverctl map normal Mod4 $i set-focused-tags $((tags | stickyTag))
    riverctl map normal Mod4+Shift $i set-view-tags $tags
    riverctl map normal Mod4+Control $i toggle-focused-tags $tags
done

# Key 0 -> Browser (Tag 10)
# Tag 10 is 1 << 9
browser_tag=$((1 << 9))
riverctl map normal Mod4 0 spawn "river-lof helium helium 10 $stickyTag"
riverctl map normal Mod4+Shift 0 set-view-tags $browser_tag
riverctl map normal Mod4+Control 0 toggle-focused-tags $browser_tag

riverctl map normal Super Backspace toggle-view-tags $stickyTag
riverctl spawn-tagmask $((((1 << 32) - 1) ^ stickyTag))

riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enabled

riverctl rule-add -app-id "zen"     tags 512
riverctl rule-add -app-id "helium"     tags 512
riverctl rule-add -app-id "*"       ssd
