name: Nix

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix flake check --no-build
      - run: nix build .#nixosConfigurations.titan.config.system.build.toplevel --no-link
      - run: nix build .#nixosConfigurations.tethys.config.system.build.toplevel --no-link
      - run: nix build .#nixosConfigurations.iapetus.config.system.build.toplevel --no-link
